// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
// the MIT License. See LICENSE in the project root for license information.
// <autogenerated> This file was generated using AutoRest. </autogenerated>

namespace SocialPlus.Client
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Search operations.
    /// </summary>
    public partial interface ISearch
    {
        /// <summary>
        /// Search topics with a query
        /// </summary>
        /// The query string will be searched across hashtags, topic titles,
        /// and topic texts,
        /// and matching results will be returned.
        /// 
        /// If the query string contains only hashtags, e.g. #foo
        /// #bar, then only the hashtags
        /// in topics will be searched.
        /// 
        /// Query string supports the following operators:
        /// - suffix: "foo*"
        /// - and: "foo+bar"
        /// - or: "foo|bar"
        /// - not: "-foo"
        /// - phrase: ""foo bar""
        /// - precedence: "foo+(bar|baz)"
        /// You need to escape * if it is at the end of a word,
        /// and - if it is at the start of a word.
        /// Default behavior is to use and, so if you use
        /// whitespace to separate words,
        /// such as "foo bar", that is equivalent to "foo+bar".
        /// <param name='query'>
        /// Search query
        /// </param>
        /// <param name='authorization'>
        /// Format is: "Scheme CredentialsList". Possible values are:
        /// 
        /// - Anon AK=AppKey
        /// 
        /// - SocialPlus TK=SessionToken
        /// 
        /// - Facebook AK=AppKey|TK=AccessToken
        /// 
        /// - Google AK=AppKey|TK=AccessToken
        /// 
        /// - Twitter AK=AppKey|RT=RequestToken|TK=AccessToken
        /// 
        /// - Microsoft AK=AppKey|TK=AccessToken
        /// 
        /// - AADS2S AK=AppKey|[UH=UserHandle]|TK=AADToken
        /// </param>
        /// <param name='cursor'>
        /// Current read cursor
        /// </param>
        /// <param name='limit'>
        /// Number of items to return
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<FeedResponseTopicView>> GetTopicsWithHttpMessagesAsync(string query, string authorization, int? cursor = default(int?), int? limit = default(int?), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Search users with a query
        /// </summary>
        /// The query string will be searched across the full name of users
        /// and matching results will be returned.
        /// 
        /// Query string supports the following operators:
        /// - suffix: "foo*"
        /// - and: "foo+bar"
        /// - or: "foo|bar"
        /// - not: "-foo"
        /// - phrase: ""foo bar""
        /// - precedence: "foo+(bar|baz)"
        /// You need to escape * if it is at the end of a word,
        /// and - if it is at the start of a word.
        /// Default behavior is to use and, so if you use
        /// whitespace to separate words,
        /// such as "foo bar", that is equivalent to "foo+bar".
        /// <param name='query'>
        /// Search query
        /// </param>
        /// <param name='authorization'>
        /// Format is: "Scheme CredentialsList". Possible values are:
        /// 
        /// - Anon AK=AppKey
        /// 
        /// - SocialPlus TK=SessionToken
        /// 
        /// - Facebook AK=AppKey|TK=AccessToken
        /// 
        /// - Google AK=AppKey|TK=AccessToken
        /// 
        /// - Twitter AK=AppKey|RT=RequestToken|TK=AccessToken
        /// 
        /// - Microsoft AK=AppKey|TK=AccessToken
        /// 
        /// - AADS2S AK=AppKey|[UH=UserHandle]|TK=AADToken
        /// </param>
        /// <param name='cursor'>
        /// Current read cursor
        /// </param>
        /// <param name='limit'>
        /// Number of items to return
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<FeedResponseUserCompactView>> GetUsersWithHttpMessagesAsync(string query, string authorization, int? cursor = default(int?), int? limit = default(int?), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
