// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
// the MIT License. See LICENSE in the project root for license information.
// <autogenerated> This file was generated using AutoRest. </autogenerated>

namespace SocialPlus.Client
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// The Embedded Social interface to clients is a RESTful API which is
    /// documented here.
    /// </summary>
    public partial interface ISocialPlusClient : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IBlobs.
        /// </summary>
        IBlobs Blobs { get; }

        /// <summary>
        /// Gets the IBuilds.
        /// </summary>
        IBuilds Builds { get; }

        /// <summary>
        /// Gets the IComments.
        /// </summary>
        IComments Comments { get; }

        /// <summary>
        /// Gets the ITopicComments.
        /// </summary>
        ITopicComments TopicComments { get; }

        /// <summary>
        /// Gets the IHashtags.
        /// </summary>
        IHashtags Hashtags { get; }

        /// <summary>
        /// Gets the IImages.
        /// </summary>
        IImages Images { get; }

        /// <summary>
        /// Gets the ITopicLikes.
        /// </summary>
        ITopicLikes TopicLikes { get; }

        /// <summary>
        /// Gets the IReplyLikes.
        /// </summary>
        IReplyLikes ReplyLikes { get; }

        /// <summary>
        /// Gets the ICommentLikes.
        /// </summary>
        ICommentLikes CommentLikes { get; }

        /// <summary>
        /// Gets the IMyNotifications.
        /// </summary>
        IMyNotifications MyNotifications { get; }

        /// <summary>
        /// Gets the IMyPins.
        /// </summary>
        IMyPins MyPins { get; }

        /// <summary>
        /// Gets the IMyPushRegistrations.
        /// </summary>
        IMyPushRegistrations MyPushRegistrations { get; }

        /// <summary>
        /// Gets the IReplies.
        /// </summary>
        IReplies Replies { get; }

        /// <summary>
        /// Gets the ICommentReplies.
        /// </summary>
        ICommentReplies CommentReplies { get; }

        /// <summary>
        /// Gets the IUserReports.
        /// </summary>
        IUserReports UserReports { get; }

        /// <summary>
        /// Gets the ITopicReports.
        /// </summary>
        ITopicReports TopicReports { get; }

        /// <summary>
        /// Gets the IReplyReports.
        /// </summary>
        IReplyReports ReplyReports { get; }

        /// <summary>
        /// Gets the ICommentReports.
        /// </summary>
        ICommentReports CommentReports { get; }

        /// <summary>
        /// Gets the ISearch.
        /// </summary>
        ISearch Search { get; }

        /// <summary>
        /// Gets the ISessions.
        /// </summary>
        ISessions Sessions { get; }

        /// <summary>
        /// Gets the IRequestTokens.
        /// </summary>
        IRequestTokens RequestTokens { get; }

        /// <summary>
        /// Gets the IUserFollowers.
        /// </summary>
        IUserFollowers UserFollowers { get; }

        /// <summary>
        /// Gets the IMyPendingUsers.
        /// </summary>
        IMyPendingUsers MyPendingUsers { get; }

        /// <summary>
        /// Gets the IMyFollowers.
        /// </summary>
        IMyFollowers MyFollowers { get; }

        /// <summary>
        /// Gets the IMyFollowing.
        /// </summary>
        IMyFollowing MyFollowing { get; }

        /// <summary>
        /// Gets the IMyBlockedUsers.
        /// </summary>
        IMyBlockedUsers MyBlockedUsers { get; }

        /// <summary>
        /// Gets the IUserFollowing.
        /// </summary>
        IUserFollowing UserFollowing { get; }

        /// <summary>
        /// Gets the ITopics.
        /// </summary>
        ITopics Topics { get; }

        /// <summary>
        /// Gets the IMyTopics.
        /// </summary>
        IMyTopics MyTopics { get; }

        /// <summary>
        /// Gets the IMyAppFollowing.
        /// </summary>
        IMyAppFollowing MyAppFollowing { get; }

        /// <summary>
        /// Gets the IMyApps.
        /// </summary>
        IMyApps MyApps { get; }

        /// <summary>
        /// Gets the IMyLikes.
        /// </summary>
        IMyLikes MyLikes { get; }

        /// <summary>
        /// Gets the IMyLinkedAccounts.
        /// </summary>
        IMyLinkedAccounts MyLinkedAccounts { get; }

        /// <summary>
        /// Gets the IUsers.
        /// </summary>
        IUsers Users { get; }

        /// <summary>
        /// Gets the IUserTopics.
        /// </summary>
        IUserTopics UserTopics { get; }

    }
}
