// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
// the MIT License. See LICENSE in the project root for license information.
// <autogenerated> This file was generated using AutoRest. </autogenerated>

namespace SocialPlus.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Response from get request token response
    /// </summary>
    public partial class GetRequestTokenResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetRequestTokenResponse class.
        /// </summary>
        public GetRequestTokenResponse() { }

        /// <summary>
        /// Initializes a new instance of the GetRequestTokenResponse class.
        /// </summary>
        public GetRequestTokenResponse(string requestToken)
        {
            RequestToken = requestToken;
        }

        /// <summary>
        /// Gets or sets request token from identity provider
        /// </summary>
        [JsonProperty(PropertyName = "requestToken")]
        public string RequestToken { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (RequestToken == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RequestToken");
            }
        }
    }
}
