// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
// the MIT License. See LICENSE in the project root for license information.
// <autogenerated> This file was generated using AutoRest. </autogenerated>

namespace SocialPlus.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Response from get topic by name
    /// </summary>
    public partial class GetTopicByNameResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetTopicByNameResponse class.
        /// </summary>
        public GetTopicByNameResponse() { }

        /// <summary>
        /// Initializes a new instance of the GetTopicByNameResponse class.
        /// </summary>
        public GetTopicByNameResponse(string topicHandle)
        {
            TopicHandle = topicHandle;
        }

        /// <summary>
        /// Gets or sets topic handle of the response
        /// </summary>
        [JsonProperty(PropertyName = "topicHandle")]
        public string TopicHandle { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (TopicHandle == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TopicHandle");
            }
        }
    }
}
