// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
// the MIT License. See LICENSE in the project root for license information.
// <autogenerated> This file was generated using AutoRest. </autogenerated>

namespace SocialPlus.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Request to post (create) a report for content
    /// </summary>
    public partial class PostReportRequest
    {
        /// <summary>
        /// Initializes a new instance of the PostReportRequest class.
        /// </summary>
        public PostReportRequest() { }

        /// <summary>
        /// Initializes a new instance of the PostReportRequest class.
        /// </summary>
        public PostReportRequest(Reason reason)
        {
            Reason = reason;
        }

        /// <summary>
        /// Gets or sets report reason. Possible values include:
        /// 'ThreatsCyberbullyingHarassment',
        /// 'ChildEndangermentExploitation', 'OffensiveContent',
        /// 'VirusSpywareMalware', 'ContentInfringement', 'Other', 'None'
        /// </summary>
        [JsonProperty(PropertyName = "reason")]
        public Reason Reason { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
        }
    }
}
