// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
// the MIT License. See LICENSE in the project root for license information.
// <autogenerated> This file was generated using AutoRest. </autogenerated>

namespace SocialPlus.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Request to put (update) notifications status
    /// </summary>
    public partial class PutNotificationsStatusRequest
    {
        /// <summary>
        /// Initializes a new instance of the PutNotificationsStatusRequest
        /// class.
        /// </summary>
        public PutNotificationsStatusRequest() { }

        /// <summary>
        /// Initializes a new instance of the PutNotificationsStatusRequest
        /// class.
        /// </summary>
        public PutNotificationsStatusRequest(string readActivityHandle = default(string))
        {
            ReadActivityHandle = readActivityHandle;
        }

        /// <summary>
        /// Gets or sets last read activity handle
        /// </summary>
        [JsonProperty(PropertyName = "readActivityHandle")]
        public string ReadActivityHandle { get; set; }

    }
}
