// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
// the MIT License. See LICENSE in the project root for license information.
// <autogenerated> This file was generated using AutoRest. </autogenerated>

namespace SocialPlus.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Request to put (update) topic
    /// </summary>
    public partial class PutTopicRequest
    {
        /// <summary>
        /// Initializes a new instance of the PutTopicRequest class.
        /// </summary>
        public PutTopicRequest() { }

        /// <summary>
        /// Initializes a new instance of the PutTopicRequest class.
        /// </summary>
        public PutTopicRequest(string text, string title = default(string), string categories = default(string))
        {
            Title = title;
            Text = text;
            Categories = categories;
        }

        /// <summary>
        /// Gets or sets topic title
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets topic text
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

        /// <summary>
        /// Gets or sets topic categories
        /// </summary>
        [JsonProperty(PropertyName = "categories")]
        public string Categories { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Text == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Text");
            }
        }
    }
}
