// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
// the MIT License. See LICENSE in the project root for license information.
// <autogenerated> This file was generated using AutoRest. </autogenerated>

namespace SocialPlus.Client.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for TimeRange.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TimeRange
    {
        [EnumMember(Value = "Today")]
        Today,
        [EnumMember(Value = "ThisWeek")]
        ThisWeek,
        [EnumMember(Value = "ThisMonth")]
        ThisMonth,
        [EnumMember(Value = "AllTime")]
        AllTime
    }
}
